name: 🧪 End-to-end tests

inputs:
  url:
    required: false
    type: string
  auth-bypass-token:
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: 📥 Install dependencies
      shell: 'bash'
      run: npm ci

    - name: 📦 Build
      shell: 'bash'
      run: npm run build

    - name: 💾 Turbo cache
      id: turbo-cache
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
      with:
        path: |
          node_modules/.cache/turbo
          **/.turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: 📄 Get installed Playwright version
      shell: 'bash'
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright -m 1 | sed 's/.*@//')"  >> $GITHUB_ENV

    - name: 💾 Cache Playwright binaries
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: 💽 Install Playwright Browsers (all)
      shell: 'bash'
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium

    - name: 💽 Install Playwright (only system deps)
      shell: 'bash'
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps chromium

    - name: 🍄 Run Playwright tests
      shell: 'bash'
      run: URL=${{ inputs.url }} AUTH_BYPASS_TOKEN=${{ inputs.auth-bypass-token }} npx playwright test

    - name: 🗒 Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: playwright-report
        path: ./playwright-report/
        retention-days: 30
